import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
import pandas as pd

from app.models.report import Report
from app.models.emission_activity import EmissionActivity, ActivityStatus, EmissionScope


class ReportDataExtractor:
    """Helper to pull all necessary data for a report."""
    @staticmethod
    def get_data(report_id):
        report = Report.query.get(report_id)
        if not report:
            raise ValueError(f"Report {report_id} not found")

        # Get all validated/audited activities for the organization
        activities = EmissionActivity.query.filter(
            EmissionActivity.organization_id == report.organization_id,
            EmissionActivity.status.in_([ActivityStatus.VALIDATED, ActivityStatus.AUDITED])
        ).all()

        # Calculate breakdown by scope and category
        scope_totals = {
            "Scope 1": 0.0,
            "Scope 2": 0.0,
            "Scope 3": 0.0
        }
        category_totals = {}
        
        for a in activities:
            if not a.co2e_result:
                continue
            scope_totals[a.scope.value] += a.co2e_result
            category_totals[a.category] = category_totals.get(a.category, 0.0) + a.co2e_result

        total_emissions = sum(scope_totals.values())
        
        # Sort categories by highest emission
        sorted_categories = dict(sorted(category_totals.items(), key=lambda item: item[1], reverse=True))

        # Prepare activity rows for "Notes de Calcul"
        rows = []
        for a in activities:
            if not a.co2e_result:
                continue
            
            # Hypothesis string
            unit = a.quantity_unit or a.ademe_factor_unit or "unit"
            hypo = f"{a.quantity} {unit} × {a.ademe_factor_value} = {a.co2e_result:,.2f} kgCO2e"
            
            rows.append({
                "scope": a.scope.value,
                "category": a.category,
                "description": a.description or "-",
                "factor_name": a.ademe_factor_name or "Custom Factor",
                "factor_id": a.ademe_factor_id or "Custom",
                "factor_value": f"{a.ademe_factor_value} {a.ademe_factor_unit or ''}",
                "hypothesis": hypo,
                "co2e": a.co2e_result
            })

        # Sort rows by scope then category
        rows.sort(key=lambda x: (x["scope"], x["category"]))

        return {
            "report": report,
            "organization": report.organization,
            "scope_totals": scope_totals,
            "category_totals": sorted_categories,
            "total_emissions": total_emissions,
            "activities": rows,
            "date_generated": datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
        }


from reportlab.platypus import BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.graphics.shapes import Drawing, String
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart

def add_header_footer(canvas, doc):
    """Draws consistent headers and footers on every page except the cover."""
    if doc.page == 1:
         return
    canvas.saveState()
    canvas.setFont('Helvetica', 9)
    canvas.setStrokeColor(colors.HexColor('#E5E7EB'))
    # Header
    canvas.drawString(50, A4[1] - 30, "GreenLedger Carbon Report")
    canvas.drawRightString(A4[0] - 50, A4[1] - 30, doc.org_name)
    canvas.line(50, A4[1] - 35, A4[0] - 50, A4[1] - 35)
    # Footer
    canvas.line(50, 40, A4[0] - 50, 40)
    canvas.drawString(50, 25, "Confidential - Generated by GreenLedger")
    canvas.drawRightString(A4[0] - 50, 25, f"Page {doc.page}")
    canvas.restoreState()

class PDFReportGenerator:
    """Generates a high-quality PDF report."""
    def generate(self, report_id):
        data = ReportDataExtractor.get_data(report_id)
        buffer = io.BytesIO()
        
        # Setup advanced doc template
        doc = BaseDocTemplate(
            buffer, pagesize=A4,
            rightMargin=50, leftMargin=50,
            topMargin=50, bottomMargin=50
        )
        # Store org name for the header/footer callback
        doc.org_name = data['organization'].name
        
        frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id='normal')
        template = PageTemplate(id='Main', frames=frame, onPage=add_header_footer)
        doc.addPageTemplates([template])

        elements = []
        styles = getSampleStyleSheet()
        
        # Custom Styles
        title_style = ParagraphStyle(
            'CustomTitle', parent=styles['Title'],
            fontSize=32, textColor=colors.HexColor('#111814'),
            spaceAfter=40, fontName='Helvetica-Bold', alignment=1
        )
        subtitle_style = ParagraphStyle(
            'CustomSubTitle', parent=styles['Heading2'],
            fontSize=18, textColor=colors.HexColor('#618975'),
            spaceAfter=20, alignment=1
        )
        heading_style = ParagraphStyle(
            'CustomH1', parent=styles['Heading1'],
            fontSize=18, textColor=colors.HexColor('#111814'),
            spaceAfter=15, fontName='Helvetica-Bold',
            borderPadding=(0,0,5,0)
        )
        normal_style = styles['Normal']
        normal_style.fontSize = 11
        normal_style.leading = 16

        # ==========================================
        # 1. COVER PAGE
        # ==========================================
        elements.append(Spacer(1, 150))
        elements.append(Paragraph(f"Carbon Footprint Report", title_style))
        elements.append(Paragraph(f"{data['organization'].name}", subtitle_style))
        if data['report'].period_label:
            elements.append(Paragraph(f"Reporting Period: {data['report'].period_label}", subtitle_style))
        elements.append(Spacer(1, 150))
        elements.append(Paragraph(f"Status: {data['report'].status.value.replace('_', ' ').title()}", subtitle_style))
        elements.append(Paragraph(f"Generated on: {data['date_generated']}", subtitle_style))
        elements.append(PageBreak())

        # ==========================================
        # 2. METHODOLOGY & INTRODUCTION
        # ==========================================
        elements.append(Paragraph("Introduction & Methodology", heading_style))
        intro_text = """
        This report outlines the greenhouse gas (GHG) emissions associated with the operations of the organization. 
        It has been generated using the GreenLedger platform, conforming to the structural principles of the GHG Protocol.
        <br/><br/>
        All calculations found within this document utilize emission factors sourced from verified databases (e.g., ADEME Base Empreinte). 
        The underlying mathematical hypothesis for every emission activity is based on the formula:
        <br/><br/>
        <b>Activity Data (Quantity) × Emission Factor Value = CO2e Result (kgCO2e)</b>
        <br/><br/>
        Emissions are categorized into three standard scopes to provide clear visibility into direct vs. indirect climate impact.
        """
        if data['report'].summary:
            intro_text += f"<br/><br/><b>Executive Summary:</b><br/>{data['report'].summary}"
            
        elements.append(Paragraph(intro_text, normal_style))
        elements.append(PageBreak())

        # ==========================================
        # 3. DASHBOARD & METRICS
        # ==========================================
        elements.append(Paragraph("Emission Overview", heading_style))
        
        # Calculate percentages and draw pie chart
        total = data['total_emissions'] or 1
        pie_data = []
        pie_labels = []
        for scope, amount in data['scope_totals'].items():
            if amount > 0:
                pct = (amount / total) * 100
                pie_data.append(amount)
                pie_labels.append(f"{scope} ({pct:.1f}%)")
                
        if pie_data:
            d = Drawing(400, 200)
            pc = Pie()
            pc.x = 100
            pc.y = 20
            pc.width = 150
            pc.height = 150
            pc.data = pie_data
            pc.labels = pie_labels
            pc.sideLabels = True
            
            # Custom colors to match brand
            palette = [colors.HexColor('#168A53'), colors.HexColor('#2A4035'), colors.HexColor('#618975')]
            for i, color in enumerate(palette[:len(pie_data)]):
                pc.slices[i].fillColor = color
            
            d.add(pc)
            elements.append(d)
            elements.append(Spacer(1, 30))
        
        # Bar Chart for Top Categories
        if data['category_totals']:
            elements.append(Paragraph("Emissions by Category (Top 5)", heading_style))
            d_bar = Drawing(400, 200)
            bc = VerticalBarChart()
            bc.x = 50
            bc.y = 50
            bc.height = 125
            bc.width = 300
            
            # Take top 5 categories
            top_cats = list(data['category_totals'].items())[:5]
            bc.data = [[v for k, v in top_cats]]
            cat_names = [k[:15] + "..." if len(k) > 15 else k for k, v in top_cats]
            bc.categoryAxis.categoryNames = cat_names
            
            bc.bars[0].fillColor = colors.HexColor('#618975')
            bc.valueAxis.valueMin = 0
            
            d_bar.add(bc)
            elements.append(d_bar)
            elements.append(Spacer(1, 30))

        # Data Table
        overview_data = [["Scope", "Emissions (kgCO2e)", "% of Total"]]
        for scope, amount in data['scope_totals'].items():
            pct = (amount / total) * 100
            overview_data.append([scope, f"{amount:,.2f}", f"{pct:.1f}%"])
        overview_data.append(["Total", f"{data['total_emissions']:,.2f}", "100.0%"])

        t = Table(overview_data, colWidths=[150, 150, 100])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#168A53')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F9FAFB')),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#E5E7EB')),
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'), # Total row bold
        ]))
        elements.append(t)
        elements.append(PageBreak())

        # ==========================================
        # 4. NOTES DE CALCUL
        # ==========================================
        elements.append(Paragraph("Notes de Calcul (Detailed Calculations)", heading_style))
        elements.append(Paragraph("Complete breakdown of every active emission record and its exact calculation formula.", normal_style))
        elements.append(Spacer(1, 20))

        calc_data = [["Scope/Category", "Description", "ADEME ID", "Factor Value", "Hypothesis (Qty × EF)"]]
        for row in data['activities']:
            sc = f"{row['scope']}\n{row['category']}"
            calc_data.append([
                sc, 
                row['description'], 
                row['factor_id'], 
                row['factor_value'], 
                row['hypothesis']
            ])

        t2 = Table(calc_data, colWidths=[90, 120, 80, 80, 130])
        t2.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2A4035')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#E5E7EB')),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('WORDWRAP', (0, 0), (-1, -1), True)
        ]))
        elements.append(t2)

        # Build PDF
        doc.build(elements)
        buffer.seek(0)
        return buffer


class DocxReportGenerator:
    """Generates a formatted Word document report."""
    def generate(self, report_id):
        data = ReportDataExtractor.get_data(report_id)
        doc = Document()
        
        # ==========================================
        # 1. COVER PAGE
        # ==========================================
        # Add a big gap at the top
        for _ in range(5):
            doc.add_paragraph()
            
        title = doc.add_heading('Carbon Footprint Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        org = doc.add_heading(f"{data['organization'].name}", level=1)
        org.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        if data['report'].period_label:
            p = doc.add_paragraph(f"Reporting Period: {data['report'].period_label}")
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            
        for _ in range(5):
            doc.add_paragraph()
            
        st = doc.add_paragraph(f"Status: {data['report'].status.value.replace('_', ' ').title()}")
        st.alignment = WD_ALIGN_PARAGRAPH.CENTER
        dt = doc.add_paragraph(f"Generated on: {data['date_generated']}")
        dt.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_page_break()

        # ==========================================
        # 2. METHODOLOGY & INTRODUCTION
        # ==========================================
        doc.add_heading('Introduction & Methodology', level=1)
        
        intro_text = (
            "This report outlines the greenhouse gas (GHG) emissions associated with the operations of the organization. "
            "It has been generated using the GreenLedger platform, conforming to the structural principles of the GHG Protocol.\n\n"
            "All calculations found within this document utilize emission factors sourced from verified databases (e.g., ADEME Base Empreinte). "
            "The underlying mathematical hypothesis for every emission activity is based on the formula:\n\n"
            "Activity Data (Quantity) × Emission Factor Value = CO2e Result (kgCO2e)\n\n"
            "Emissions are categorized into three standard scopes to provide clear visibility into direct vs. indirect climate impact."
        )
        doc.add_paragraph(intro_text)
        
        if data['report'].summary:
            doc.add_heading('Executive Summary', level=2)
            doc.add_paragraph(data['report'].summary)
            
        doc.add_page_break()

        # ==========================================
        # 3. DASHBOARD & METRICS
        # ==========================================
        doc.add_heading('Emission Overview', level=1)
        table = doc.add_table(rows=1, cols=3)
        table.style = 'Light Shading Accent 1'
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Scope'
        hdr_cells[1].text = 'Emissions (kgCO2e)'
        hdr_cells[2].text = '% of Total'
        
        total = data['total_emissions'] or 1
        for scope, amount in data['scope_totals'].items():
            row_cells = table.add_row().cells
            row_cells[0].text = scope
            row_cells[1].text = f"{amount:,.2f}"
            row_cells[2].text = f"{(amount / total) * 100:.1f}%"
            
        row_cells = table.add_row().cells
        row_cells[0].text = "Total"
        row_cells[1].text = f"{data['total_emissions']:,.2f}"
        row_cells[2].text = "100.0%"
        
        doc.add_page_break()
        
        # ==========================================
        # 4. NOTES DE CALCUL
        # ==========================================
        doc.add_heading('Notes de Calcul (Detailed Calculations)', level=1)
        doc.add_paragraph("This section details the hypothesis, emission factors, and raw quantities used to arrive at the final numbers.")
        
        calc_table = doc.add_table(rows=1, cols=5)
        calc_table.style = 'Light Grid Accent 1'
        calc_hdr = calc_table.rows[0].cells
        calc_hdr[0].text = 'Scope/Category'
        calc_hdr[1].text = 'Description'
        calc_hdr[2].text = 'ADEME ID'
        calc_hdr[3].text = 'Factor Value'
        calc_hdr[4].text = 'Hypothesis (Qty × EF)'
        
        for row in data['activities']:
            rc = calc_table.add_row().cells
            rc[0].text = f"{row['scope']}\n{row['category']}"
            rc[1].text = row['description']
            rc[2].text = row['factor_id']
            rc[3].text = row['factor_value']
            rc[4].text = row['hypothesis']
            
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer


from openpyxl.chart import PieChart, BarChart, Reference

class ExcelReportGenerator:
    """Generates a multi-sheet Excel workbook report."""
    def generate(self, report_id):
        data = ReportDataExtractor.get_data(report_id)
        
        buffer = io.BytesIO()
        wb = openpyxl.Workbook()
        
        # Format Styles
        header_fill = PatternFill(start_color="168A53", end_color="168A53", fill_type="solid")
        header_font = Font(color="FFFFFF", bold=True)
        thin_border = Border(left=Side(style='thin'), right=Side(style='thin'), 
                             top=Side(style='thin'), bottom=Side(style='thin'))
                             
        # --- Sheet 1: Dashboard ---
        ws1 = wb.active
        ws1.title = "Overview Dashboard"
        
        ws1["A1"] = "Carbon Footprint Report Overview"
        ws1["A1"].font = Font(size=16, bold=True)
        ws1["A3"] = "Organization:"
        ws1["B3"] = data['organization'].name
        ws1["A4"] = "Total Emissions (kgCO2e):"
        ws1["B4"] = data['total_emissions']
        
        ws1.merge_cells('A6:F6')
        ws1["A6"] = "Methodology: Activity Data (Quantity) × Emission Factor Value = CO2e Result (kgCO2e)"
        ws1["A6"].font = Font(italic=True, color="618975")
        
        # Scope Table
        ws1["A8"] = "Scope"
        ws1["B8"] = "Emissions (kgCO2e)"
        ws1["A8"].fill = header_fill
        ws1["A8"].font = header_font
        ws1["B8"].fill = header_fill
        ws1["B8"].font = header_font
        
        row_idx = 9
        for scope, amount in data['scope_totals'].items():
            ws1.cell(row=row_idx, column=1, value=scope)
            ws1.cell(row=row_idx, column=2, value=amount)
            row_idx += 1
            
        ws1.column_dimensions['A'].width = 25
        ws1.column_dimensions['B'].width = 20
        
        # Add Excel Pie Chart linked to Scope Table
        pie = PieChart()
        labels = Reference(ws1, min_col=1, min_row=9, max_row=row_idx-1)
        values = Reference(ws1, min_col=2, min_row=8, max_row=row_idx-1)
        pie.add_data(values, titles_from_data=True)
        pie.set_categories(labels)
        pie.title = "Emissions by Scope"
        
        # Place the chart to the right of the table
        ws1.add_chart(pie, "D8")
        
        # Add Category Bar Chart Data
        start_cat_row = row_idx + 2
        ws1.cell(row=start_cat_row, column=1, value="Top Categories").font = header_font
        ws1.cell(row=start_cat_row, column=1).fill = header_fill
        ws1.cell(row=start_cat_row, column=2, value="Emissions").font = header_font
        ws1.cell(row=start_cat_row, column=2).fill = header_fill
        
        cat_row_idx = start_cat_row + 1
        top_cats = list(data['category_totals'].items())[:5] # Top 5
        for cat, amount in top_cats:
            ws1.cell(row=cat_row_idx, column=1, value=cat)
            ws1.cell(row=cat_row_idx, column=2, value=amount)
            cat_row_idx += 1
            
        if top_cats:
            bar = BarChart()
            bar.type = "col"
            bar.style = 10
            bar.title = "Top 5 Categories"
            bar.y_axis.title = "kgCO2e"
            
            c_data = Reference(ws1, min_col=2, min_row=start_cat_row, max_row=cat_row_idx-1)
            c_cats = Reference(ws1, min_col=1, min_row=start_cat_row+1, max_row=cat_row_idx-1)
            bar.add_data(c_data, titles_from_data=True)
            bar.set_categories(c_cats)
            
            # Place the bar chart below the pie chart
            ws1.add_chart(bar, "D24")
        
        # --- Sheet 2: Notes de Calcul ---
        ws2 = wb.create_sheet(title="Notes de Calcul")
        headers = ["Scope", "Category", "Description", "ADEME ID", "Factor Value", "Hypothesis", "CO2e Result (kg)"]
        
        for col, h in enumerate(headers, 1):
            cell = ws2.cell(row=1, column=col, value=h)
            cell.fill = header_fill
            cell.font = header_font
            cell.border = thin_border
            
        for row_idx, r in enumerate(data['activities'], 2):
            ws2.cell(row=row_idx, column=1, value=r['scope']).border = thin_border
            ws2.cell(row=row_idx, column=2, value=r['category']).border = thin_border
            ws2.cell(row=row_idx, column=3, value=r['description']).border = thin_border
            ws2.cell(row=row_idx, column=4, value=r['factor_id']).border = thin_border
            ws2.cell(row=row_idx, column=5, value=r['factor_value']).border = thin_border
            ws2.cell(row=row_idx, column=6, value=r['hypothesis']).border = thin_border
            ws2.cell(row=row_idx, column=7, value=r['co2e']).border = thin_border
            
        # Adjust widths
        ws2.column_dimensions['A'].width = 10
        ws2.column_dimensions['B'].width = 25
        ws2.column_dimensions['C'].width = 30
        ws2.column_dimensions['D'].width = 30
        ws2.column_dimensions['E'].width = 35
        ws2.column_dimensions['F'].width = 15
        
        wb.save(buffer)
        buffer.seek(0)
        return buffer
